export const Shops = [
    {
      name: "24/7 - Davis Ave",
      position: {x: -47.4593, y: -1756.72, z: 29.4147},
      pedModel: "mp_m_shopkeep_01",
      pedposition: {x: -46.2593, y: -1757.91, z: 28.4147},
      pedRot: 51.1867,
      items: [
        { id: 1, itemname: 'item_health_kit', displayname: 'item_health_kit', price: 15.0, category: 'Drinks', image: 'energy_drink.png' },
        { id: 2, itemname: 'item_health_kit', displayname: 'Brot', price: 5.12, category: 'Food', image: 'bread.png' },
        { id: 3, itemname: 'item_health_kit', displayname: 'Burger', price: 12.21, category: 'Food', image: 'burger.png' },
    ],
    },
    {
      name: "Test",
      position: {x: -47.4593, y: -1756.72, z: 29.4147},
      pedModel: "mp_m_shopkeep_01",
      pedposition: {x: -46.2593, y: -1757.91, z: 28.4147},
      pedRot: 51.1867,
      blipcolor: 1,
      blipsprite: 43,
      items: [
        { id: 1, itemname: 'item_health_kit', displayname: 'Health Kit', price: 15.0, category: 'Drinks', image: 'energy_drink.png' },
        { id: 2, itemname: 'item_apple', displayname: 'Burger', price: 5.12, category: 'Food', image: 'bread.png' },
        { id: 3, itemname: 'item_water', displayname: 'Water', price: 12.21, category: 'Food', image: 'burger.png' },
    ],
    },
    {
      name: "24/7 - Clinton Ave",
      position: {x: 374.162, y: 327.797, z: 103.553},
      pedModel: "mp_m_shopkeep_01",
      pedposition: {x: 372.857, y: 328.021, z: 102.553},
      pedRot: -110.819,
      items: [
        { id: 1, itemname: 'Energy Drink', displayname: 'Energy Drink', price: 15.0, category: 'Drinks', image: 'energy_drink.png' },
        { id: 2, itemname: 'item_bread', displayname: 'Brot', price: 5.12, category: 'Food', image: 'bread.png' },
        { id: 3, itemname: 'Energy Drink', displayname: 'Burger', price: 12.21, category: 'Food', image: 'burger.png' },
    ],
    },
    
    {
      name: "24/7 - San Andreas Avenue",
      position: {x: -1223.29, y: -907.582, z: 11.312},
      pedModel: "mp_m_shopkeep_01",
      pedposition: {x: -1222.44, y: -908.663, z: 11.3121},
      pedRot: 30.291,
      items: [
        { id: 1, itemname: 'Energy Drink', displayname: 'Energy Drink', price: 15.0, category: 'Drinks', image: 'energy_drink.png' },
        { id: 2, itemname: 'item_bread', displayname: 'Brot', price: 5.12, category: 'Food', image: 'bread.png' },
        { id: 3, itemname: 'Energy Drink', displayname: 'Burger', price: 12.21, category: 'Food', image: 'burger.png' },
    ],
    },
    {
      name: "24/7 - Little Seoul",
      position: {x: -705.626, y: -914.611, z: 19.2036},
      pedModel: "mp_m_shopkeep_01",
      pedposition: {x: -705.626, y: -914.611, z: 18.2036},
      pedRot: 85.726,
      items: [
        { id: 1, itemname: 'Energy Drink', displayname: 'Energy Drink', price: 15.0, category: 'Drinks', image: 'energy_drink.png' },
        { id: 2, itemname: 'item_bread', displayname: 'Brot', price: 5.12, category: 'Food', image: 'bread.png' },
        { id: 3, itemname: 'Energy Drink', displayname: 'Burger', price: 12.21, category: 'Food', image: 'burger.png' },
    ],
    },
    {
      name: "24/7 - Strawberry Ave",
      position: {x: 24.2505, y: -1345.08, z: 29.4821},
      pedModel: "mp_m_famdd_01",
      pedposition: {x: 24.2505, y: -1345.08, z: 28.4821},
      pedRot: -93.251,
      items: [
        { id: 1, itemname: 'Energy Drink', displayname: 'Energy Drink', price: 15.0, category: 'Drinks', image: 'energy_drink.png' },
        { id: 2, itemname: 'item_bread', displayname: 'Brot', price: 5.12, category: 'Food', image: 'bread.png' },
        { id: 3, itemname: 'Energy Drink', displayname: 'Burger', price: 12.21, category: 'Food', image: 'burger.png' },
    ],
    },
    {
      name: "24/7 - Vespucci Blvd",
      position: {x: 1135.5, y: -981.6, z: 46.3993},
      pedModel: "mp_m_shopkeep_01",
      pedposition: {x: 1134.09, y: -982.484, z: 45.3993},
      pedRot: 0,
      items: [
        { id: 1, itemname: 'Energy Drink', displayname: 'Energy Drink', price: 15.0, category: 'Drinks', image: 'energy_drink.png' },
        { id: 2, itemname: 'item_bread', displayname: 'Brot', price: 5.12, category: 'Food', image: 'bread.png' },
        { id: 3, itemname: 'Energy Drink', displayname: 'Burger', price: 12.21, category: 'Food', image: 'burger.png' },
    ],
    },
    {
      name: "24/7 - Mirror Park",
      position: {x: 1163.55, y: -323.934, z: 69.197},
      pedModel: "mp_m_shopkeep_01",
      pedposition: {x: 1164.83, y: -323.617, z: 68.197},
      pedRot: 92.38,
      items: [
        { id: 1, itemname: 'Energy Drink', displayname: 'Energy Drink', price: 15.0, category: 'Drinks', image: 'energy_drink.png' },
        { id: 2, itemname: 'item_bread', displayname: 'Brot', price: 5.12, category: 'Food', image: 'bread.png' },
        { id: 3, itemname: 'Energy Drink', displayname: 'Burger', price: 12.21, category: 'Food', image: 'burger.png' },
    ],
    },
    {
      name: "24/7 - Morningwood",
      position: {x: -1485.96, y: -377.96, z: 40.1479},
      pedModel: "mp_m_shopkeep_01",
      pedposition: {x: -1485.96, y: -377.96, z: 39.1479},
      pedRot: 129.749,
      items: [
        { id: 1, itemname: 'Energy Drink', displayname: 'Energy Drink', price: 15.0, category: 'Drinks', image: 'energy_drink.png' },
        { id: 2, itemname: 'item_bread', displayname: 'Brot', price: 5.12, category: 'Food', image: 'bread.png' },
        { id: 3, itemname: 'Energy Drink', displayname: 'Burger', price: 12.21, category: 'Food', image: 'burger.png' },
    ],
    },
    {
      name: "24/7 - Great Ocean Hwy",
      position: {x: -2968.09, y: 390.514, z: 14.041},
      pedModel: "mp_m_shopkeep_01",
      pedposition: {x: -2966.52, y: 390.435, z: 14.0417},
      pedRot: 88.193,
      items: [
        { id: 1, itemname: 'Energy Drink', displayname: 'Energy Drink', price: 15.0, category: 'Drinks', image: 'energy_drink.png' },
        { id: 2, itemname: 'item_bread', displayname: 'Brot', price: 5.12, category: 'Food', image: 'bread.png' },
        { id: 3, itemname: 'Energy Drink', displayname: 'Burger', price: 12.21, category: 'Food', image: 'burger.png' },
    ],
    },
    {
      name: "24/7 - Banham Canyon",
      position: {x: -3041.08, y: 585.204, z: 6.897},
      pedModel: "mp_m_shopkeep_01",
      pedposition: {x: -3040.58, y: 583.938, z: 6.89746},
      pedRot: 16.129,
      items: [
        { id: 1, itemname: 'Energy Drink', displayname: 'Energy Drink', price: 15.0, category: 'Drinks', image: 'energy_drink.png' },
        { id: 2, itemname: 'item_bread', displayname: 'Brot', price: 5.12, category: 'Food', image: 'bread.png' },
        { id: 3, itemname: 'Energy Drink', displayname: 'Burger', price: 12.21, category: 'Food', image: 'burger.png' },
    ],
    },
    {
      name: "24/7 - Barbareno Rd Chumash",
      position: {x: -3243.98, y: 1001.34, z: 11.817},
      pedModel: "mp_m_shopkeep_01",
      pedposition: {x: -3244.35, y: 1000.1, z: 12.8176},
      pedRot: 10.731,
      items: [
        { id: 1, itemname: 'Energy Drink', displayname: 'Energy Drink', price: 15.0, category: 'Drinks', image: 'energy_drink.png' },
        { id: 2, itemname: 'item_bread', displayname: 'Brot', price: 5.12, category: 'Food', image: 'bread.png' },
        { id: 3, itemname: 'Energy Drink', displayname: 'Burger', price: 12.21, category: 'Food', image: 'burger.png' },
    ],
    },
    {
      name: "24/7 - Senora Fwy North",
      position: {x: 1728.7, y: 6417.34, z: 35.0256},
      pedModel: "mp_m_shopkeep_01",
      pedposition: {x: 1728.7, y: 6417.34, z: 34.0256},
      pedRot: -119.807,
      items: [
        { id: 1, itemname: 'Energy Drink', displayname: 'Energy Drink', price: 15.0, category: 'Drinks', image: 'energy_drink.png' },
        { id: 2, itemname: 'item_bread', displayname: 'Brot', price: 5.12, category: 'Food', image: 'bread.png' },
        { id: 3, itemname: 'Energy Drink', displayname: 'Burger', price: 12.21, category: 'Food', image: 'burger.png' },
    ],
    },
    {
      name: "24/7 - Grapeseed Main St",
      position: {x: 1697.05, y: 4922.95, z: 42.052},
      pedModel: "mp_m_shopkeep_01",
      pedposition: {x: 1697.05, y: 4922.95, z: 41.052},
      pedRot: -41.935,
      items: [
        { id: 1, itemname: 'Energy Drink', displayname: 'Energy Drink', price: 15.0, category: 'Drinks', image: 'energy_drink.png' },
        { id: 2, itemname: 'item_bread', displayname: 'Brot', price: 5.12, category: 'Food', image: 'bread.png' },
        { id: 3, itemname: 'Energy Drink', displayname: 'Burger', price: 12.21, category: 'Food', image: 'burger.png' },
    ],
    },
    {
      name: "24/7 - Senora Fwy South",
      position: {x: 2676.67, y: 3280.18, z: 55.2285},
      pedModel: "mp_m_shopkeep_01",
      pedposition: {x: 2676.25, y: 3280.31, z: 54.2285},
      pedRot: -0.494739,
      items: [
        { id: 1, itemname: 'Energy Drink', displayname: 'Energy Drink', price: 15.0, category: 'Drinks', image: 'energy_drink.png' },
        { id: 2, itemname: 'item_bread', displayname: 'Brot', price: 5.12, category: 'Food', image: 'bread.png' },
        { id: 3, itemname: 'Energy Drink', displayname: 'Burger', price: 12.21, category: 'Food', image: 'burger.png' },
    ],
    },
    {
      name: "24/7 - Kpirgendwo",
      position: {x: 2555.56, y: 382.088, z: 108.609},
      pedModel: "mp_m_shopkeep_01",
      pedposition: {x: 2555.59, y: 380.862, z: 107.609},
      pedRot: -0.494739,
      items: [
        { id: 1, itemname: 'Energy Drink', displayname: 'Energy Drink', price: 15.0, category: 'Drinks', image: 'energy_drink.png' },
        { id: 2, itemname: 'item_bread', displayname: 'Brot', price: 5.12, category: 'Food', image: 'bread.png' },
        { id: 3, itemname: 'Energy Drink', displayname: 'Burger', price: 12.21, category: 'Food', image: 'burger.png' },
    ],
    }
  ]

